
version: 2
jobs:
  test:
    docker:
   
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
        
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            # python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
  build:
    environment:
      IMAGE_NAME: mohamedazab/cfc-irrigation-system
    docker:
     
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: login to  Docker Hub
          command: docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
      - run:
          name: publish to Docker Hub
          command: docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
          - test:
              filters:
                branches:
                  only: master
          - build:
              requires:
                - test
              filters:
                branches:
                  only: master   
